# SYSTEM PROPERTIES
WIDTH = 735
HEIGHT = 480
FPS = 60
TITLE = "Side Scroller"
BK = (0,0,0)


# PHYSICS
PLAYER_FRICTION = 0.12
PLAYER_ACC = 0.5
PLAYER_JUMP = 13
PLAYER_WALK_MAX = 8
PLAYER_SPRINT_MAX = 16


PLAYER_GRAVITY = 0.5

# IMG FILES
SPRITE_SHEET = 'characters.png'
TILE_SHEET = 'sheet.png'
MOON_SHEET = 'swoosh.png'
CLOUD_SHEET = 'clouds.png'
